const mongoose=require('mongoose')

const cardDetails=mongoose.Schema({

    cardName:{
        type:String,
        required:true
    },
    description:{
        type:String,
    },
    features:{
        point1:{
            type:String,
        },
        point2:{
            type:String,
        },
        point3:{
            type:String,
        },
        point4:{
            type:String,
        },
        point5:{
            type:String,
        },
        point6:{
            type:String,
        },
        point7:{
            type:String,
        },
        point8:{
            type:String,
        },
        point9:{
            type:String,
        },
        point10:{
            type:String,
        },
    },
  
    benfits:{
        point1:{
            type:String,
        },
        point2:{
            type:String,
        },
        point3:{
            type:String,
        },
        point4:{
            type:String,
        },
        point5:{
            type:String,
        },
        point6:{
            type:String,
        },
        point7:{
            type:String,
        },
        point8:{
            type:String,
        },
        point9:{
            type:String,
        },
        point10:{
            type:String,
        },
    },
})
const CardDetails=mongoose.model('cardDetails',cardDetails);
module.exports=CardDetails;